apiVersion : v1
kind : Service
metadata:
  name: clickhouse
  labels:
    env: prod
    owner: user
spec:
  clusterIP: None
  selector:
    app : clickhouse  # Selecting PODS
---
apiVersion : v1
kind : Service
metadata:
  name: clickhouse1-web
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : clickhouse # Selecting PODS
  ports:
    - name      : clickhouse-web
      protocol  : TCP
      targetPort: 8123  # Port on POD
      nodePort  : 32023  # Port on Load Balancer
      port      : 3333
  type: NodePort
---
apiVersion : v1
kind : Service
metadata:
  name: clickhouse1-remote
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : clickhouse # Selecting PODS
  ports:
    - name      : clickhouse-web
      protocol  : TCP
      targetPort: 9000  # Port on POD
      nodePort  : 32009  # Port on Load Balancer
      port      : 3333
  type: NodePort
---
apiVersion: v1
data:
  config.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <logger>
            <level>debug</level>
            <console>true</console>
            <log>/var/lib/clickhouse/logs/clickhouse-server.log</log>
                <errorlog>/var/lib/clickhouse/logs/clickhouse-server.err.log</errorlog>
                <size>1000M</size>
                <count>5</count>
        </logger>

        <query_log>
            <database>system</database>
            <table>query_log</table>
        </query_log>

        <session_log>
            <database>system</database>
            <table>session_log</table>
        </session_log>

        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_host>clickhouse</interserver_http_host>
        <interserver_http_port>9009</interserver_http_port>

        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>

        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
    <!--    <access_control_path>/var/lib/clickhouse/access/</access_control_path>-->
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <timezone>Europe/Moscow</timezone>
        <mlock_executable>false</mlock_executable>

        <remote_servers>
            <test_cluster>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                    <default_database>company_shard_1</default_database>
                        <host>clickhouse</host>
                        <password>admin</password>
                        <user>admin</user>
                    </replica>
                </shard>
            </test_cluster>
        </remote_servers>

        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>

        <jdbc_bridge>
            <host>clickhouse-jdbc</host>
            <port>9019</port>
        </jdbc_bridge>

        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
    </clickhouse>
  users.xml: |
    <?xml version="1.0"?>
    <company>
        <profiles>
            <default>
                <max_memory_usage>1000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>in_order</load_balancing>
                <max_partitions_per_insert_block>5000</max_partitions_per_insert_block>
                <log_queries>1</log_queries>
                <enable_http_compression>1</enable_http_compression>
            </default>
        </profiles>

        <users>
            <admin>
                <password>admin</password>
                <profile>default</profile>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <quota>default</quota>
            </admin>
        </users>


        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </company>
kind: ConfigMap
metadata:
  name: config-clickhouse
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: clickhouse
  labels:
    app : clickhouse
    project : test
spec:
  selector:
    matchLabels:
      project : test
  template:
    metadata:
      labels:
        app : clickhouse
        project : test
    spec:
      containers:
        - name : clickhouse
          image : aggrik/clickhouse:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/clickhouse-server
              name:  configmap-clickhouse-cfg
            - mountPath: /var/lib/clickhouse
              name: clickhouse-data
      volumes:
       - name: configmap-clickhouse-cfg
         configMap:
           defaultMode: 0755
           name: config-clickhouse
       - name: clickhouse-data
         emptyDir: {}