apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
    owner: user
  name: zkhost1
spec:
  clusterIP: None
  selector:
    app: zoo-1
  ports:
    - name      : zoo-1
      protocol  : TCP
      targetPort: 2181  # Port on POD
      port      : 2181
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
    owner: user
  name: zkhost2
spec:
  clusterIP: None
  selector:
    app: zoo-2
  ports:
    - name      : zoo-2
      protocol  : TCP
      targetPort: 2181  # Port on POD
      port      : 2181
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
    owner: user
  name: zkhost3
spec:
  clusterIP: None
  selector:
    app: zoo-3
  ports:
    - name      : zoo-3
      protocol  : TCP
      targetPort: 2181  # Port on POD
      port      : 2181