apiVersion: v1
kind: ConfigMap
metadata:
  name: zoo-run
data:
  run.sh: |-
    #!/bin/bash
    echo $1 > /home/zookeeper/data/zookeeper/myid
    /opt/zookeeper/bin/zkServer.sh start-foreground
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: zoo-1
  labels:
    app : zoo-1
    project : base
spec:
  selector:
    matchLabels:
      project: base
  template:
    metadata:
      labels:
        project: base
        app : zoo-1
    spec:
      hostname: zkhost1
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name : zoo-1
          resources: {}
          image : 10.11.4.10:31500/zookeeper_multi:latest
          imagePullPolicy : IfNotPresent
          command: ["bash", "-c", "/bin/run.sh 1"]
          volumeMounts:
            - name: zoo-1-data
              mountPath: /home/zookeeper/data/zookeeper              
            - name: configmap-zoo-1-volume
              mountPath: /bin/run.sh
              readOnly: false
              subPath: run.sh
      volumes:
       - name: zoo-1-data
         emptyDir: {}
#         hostPath:
#           path: /storage/data/zookeeper/zoo-1
#           type: DirectoryOrCreate
       - name: configmap-zoo-1-volume
         configMap:
           defaultMode: 0775
           name: zoo-run
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: zoo-2
  labels:
    app : zoo-2
    project : base
spec:
  selector:
    matchLabels:
      project: base
  template:
    metadata:
      labels:
        project: base
        app : zoo-2
    spec:
      hostname: zkhost2
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name : zoo-2
          resources: {}
          image : 10.11.4.10:31500/zookeeper_multi:latest
          imagePullPolicy : IfNotPresent
          command: ["bash", "-c", "/bin/run.sh 2"]
          volumeMounts:
            - name: zoo-2-data
              mountPath: /home/zookeeper/data/zookeeper              
            - name: configmap-zoo-2-volume
              mountPath: /bin/run.sh
              readOnly: false
              subPath: run.sh
      volumes:
       - name: zoo-2-data
         emptyDir: {}
#         hostPath:
#           path: /storage/data/zookeeper/zoo-2
#           type: DirectoryOrCreate
       - name: configmap-zoo-2-volume
         configMap:
           defaultMode: 0775
           name: zoo-run
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: zoo-3
  labels:
    app : zoo-3
    project : base
spec:
  selector:
    matchLabels:
      project: base
  template:
    metadata:
      labels:
        project: base
        app : zoo-3
    spec:
      hostname: zkhost3
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name : zoo-3
          resources: {}
          image : 10.11.4.10:31500/zookeeper_multi:latest
          imagePullPolicy : IfNotPresent
          command: ["bash", "-c", "/bin/run.sh 3"]
          volumeMounts:
            - name: zoo-3-data
              mountPath: /home/zookeeper/data/zookeeper              
            - name: configmap-zoo-3-volume
              mountPath: /bin/run.sh
              readOnly: false
              subPath: run.sh
      volumes:
       - name: zoo-3-data
         emptyDir: {}
#         hostPath:
#           path: /storage/data/zookeeper/zoo-1
#           type: DirectoryOrCreate
       - name: configmap-zoo-3-volume
         configMap:
           defaultMode: 0775
           name: zoo-run