apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-airflow-run
data:
  init.sh: |-
    #!/bin/bash
    /usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main/
    # Start postgress and create test user and db
    /etc/init.d/postgresql start 
    a=$(psql -l | awk '{print $1}' | grep airflow_db)
    if [ -z $a ]; then
       echo "INIT STARTED"
        psql --command "CREATE USER airflow WITH PASSWORD 'airflow';" 
        createdb -O airflow airflow_db
       /etc/init.d/postgresql stop
       echo "INIT FINISHED"
    else
       /etc/init.d/postgresql stop
       echo "INIT IS NOT REQUIRED"
    fi
    sleep 10
    echo "DONE"

  run.sh: |-
    #!/bin/bash
    echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/14/main/pg_hba.conf
    echo "listen_addresses='*'" >> /etc/postgresql/14/main/postgresql.conf
    /usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: postgres-airflow
  labels:
    app : postgres-airflow
    project : test
spec:
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        app : postgres-airflow
        project: test
    spec:
      containers:
        - name : postgres-airflow
          resources: {}
          image : 10.11.4.10:31500/postgresql:latest
          #image : aggrik/postgresql:latest
          command: 
          - /opt/run/run.sh    
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-airflow
              readOnly: false
            - mountPath: /opt/run/
              name: configmap-postgres-airflow-volume
              readOnly: true
      initContainers:
        - name: init-postgres-airflow
          image : 10.11.4.10:31500/postgresql:latest
          #image : aggrik/postgresql:latest
          imagePullPolicy: IfNotPresent
          command: 
          - /opt/run/init.sh    
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-airflow
            - mountPath: /opt/run/
              name: configmap-postgres-airflow-volume
              readOnly: true
      volumes:
        - name: postgresql-airflow
          emptyDir: {}
        - name: configmap-postgres-airflow-volume
          configMap:
            defaultMode: 0777
            name: postgres-airflow-run
