apiVersion : v1
kind : Service
metadata:
  name: nifi-web
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : nifi  # Selecting PODS
  ports:
    - name      : nifi-web # StateStore debug Web UI for administrators to monitor and troubleshoot
      protocol  : TCP
      targetPort: 8090       # Port on POD
      nodePort  : 31900       # Port on Load Balancer
      port      : 3322
  type: NodePort
---
apiVersion : v1
kind : Service
metadata:
  name: nifi-input-data
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : nifi  # Selecting PODS
  ports:
    - name      : nifi-input-data # StateStore debug Web UI for administrators to monitor and troubleshoot
      protocol  : TCP
      targetPort: 10000       # Port on POD
      nodePort  : 31910       # Port on Load Balancer
      port      : 3322
  type: NodePort
---
apiVersion : v1
kind : Service
metadata:
  name: nifi-registry
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : nifi  # Selecting PODS
  ports:
    - name      : nifi-registry
      protocol  : TCP
      targetPort: 18080  # Port on POD
      port      : 18080
---
apiVersion : v1
kind : Service
metadata:
  name: web-nifi-registry
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : nifi  # Selecting PODS
  ports:
    - name      : web-nifi-registry # StateStore debug Web UI for administrators to monitor and troubleshoot
      protocol  : TCP
      targetPort: 18080       # Port on POD
      nodePort  : 31901       # Port on Load Balancer
      port      : 3322
  type: NodePort