version: "3.7"  # optional since v1.27.0
services:

#контейнер для исполнения ML
  jupiter:
    container_name: jupyter
    hostname: jupyter
    image: aggrik/pyspark:latest
    environment:
      - MLFLOW_URL=http://mlflow:5000/
      - AWS_ENDPOINT_URL=http://minio:9000 
      - AWS_ACCESS_KEY_ID=adminminio
      - AWS_SECRET_ACCESS_KEY=adminminio
      # greenplum
      - GREENPLUM_HOST=greenplum
      - GREENPLUM_SCHEMA=ml
      - GREENPLUM_PORT="5432"
      - GREENPLUM_DATABASE=sdl
      - GREENPLUM_LOGIN=gpadmin
      - GREENPLUM_PASSWORD=gpadmin
      # tarantool
      - TARANTOOL_HOST=<указать свой адрес>
      - TARANTOOL_PORT="3301"
      - TARANTOOL_LOGIN=admin
      - TARANTOOL_PASSWORD=admin      
    ports:
      - 8889:8888 #jupyter
    command: ["/bin/bash", "-c","/home/sdl/.local/bin/jupyter-lab --ip jupyter --no-browser --NotebookApp.token='822fce15430e96de9bc18fedf9f938796db4c7927f912028'"]
  
