apiVersion: v1
kind: Secret
metadata:
  name: connection-params
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW5taW5pbw==
  AWS_SECRET_ACCESS_KEY: YWRtaW5taW5pbw==
  GREENPLUM_LOGIN: Z3BhZG1pbg==
  GREENPLUM_PASSWORD: Z3BhZG1pbg==
  TARANTOOL_LOGIN: YWRtaW4=
  TARANTOOL_PASSWORD: YWRtaW4=
  CLICKHOUSE_LOGIN: YWRtaW4=
  CLICKHOUSE_PASSWORD: YWRtaW4=
  GITBUCKET_LOGIN: cm9vdA==
  GITBUCKET_PASSWORD: cm9vdA==
  GIT_URL: aHR0cDovL2dpdGJ1Y2tldC1pbnQ6ODA4MC9naXRidWNrZXQ=
  MLFLOW_LOGIN: YWRtaW4=
  MLFLOW_PASSWORD: cGFzc3dvcmQ=