apiVersion : v1
kind : Service
metadata:
  name: superset-web
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : superset # Selecting PODS
  ports:
    - name      : hue
      protocol  : TCP
      targetPort: 8088  # Port on POD
      nodePort  : 32699  # Port on Load Balancer
      port      : 3333
  type: NodePort
---
apiVersion : v1
kind : Service
metadata:
  name: redis-for-superset
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : redis-superset  # Selecting PODS
  ports:
    - name      : redis-superset
      protocol  : TCP
      targetPort: 6379  # Port on POD
      port      : 6379
---
apiVersion : v1
kind : Service
metadata:
  name: superset
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : superset # Selecting PODS
  clusterIP: None