---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greenplum-connect
data:
  greenplum.yaml: |-
    databases:
    - database_name: greenplum
      sqlalchemy_uri: postgresql+psycopg2://gpadmin:gpadmin@greenplum:5432/sdl
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: superset
  labels:
    app : superset
    project : test
spec:
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        app : superset
        project: test
    spec:
      initContainers:
        - name: init-superset
          envFrom:
          - configMapRef:
              name: superset-envs
          image : aggrik/superset:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "/app/docker/docker-init.sh && superset import_datasources -p /app/datasources/greenplum.yaml"]
          volumeMounts:
            - mountPath: /app/docker
              name: configmap-superset-config
            - name: configmap-superset-server-prop
              mountPath: /app/pythonpath/superset_config.py
              readOnly: false
              subPath: superset_config.py
            - mountPath: /app/datasources
              name: greenplum-connect
      containers:
        - name : superset
          resources: {}
          envFrom:
          - configMapRef:
              name: superset-envs
          image : aggrik/superset:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "/app/docker/docker-bootstrap.sh app-gunicorn"]
          #command: ["bash", "-c", "tail -f"]
          volumeMounts:
            - mountPath: /app/docker
              name: configmap-superset-config              
            - name: configmap-superset-server-prop
              mountPath: /app/pythonpath/superset_config.py
              readOnly: false
              subPath: superset_config.py
      volumes:
       - name: configmap-superset-server-prop
         configMap:
           defaultMode: 0775
           name: superset-props
       - name: configmap-superset-config
         configMap:
           defaultMode: 0775
           name: config-superset
       - name: greenplum-connect
         configMap:
           defaultMode: 0777
           name: greenplum-connect          
