apiVersion : v1
kind : Service
metadata:
  name: postgres-superset
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : postgres-superset # Selecting PODS
  ports:
    - name      : postgres-for-superset
      protocol  : TCP
      targetPort: 5432  # Port on POD
      port      : 5432