apiVersion : v1
kind : Service
metadata:
  name: tarantool
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : tarantool # Selecting PODS
  ports:
    - name      : tarantool-int
      protocol  : TCP
      targetPort: 3301  # Port on POD
      port      : 3301
---
apiVersion : v1
kind : Service
metadata:
  name: tarantool-ext
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : tarantool  # Selecting PODS
  ports:
    - name      : tarantool-ext
      protocol  : TCP
      targetPort: 3301       # Port on POD
      nodePort  : 32031      # Port on Load Balancer
      port      : 3301
  type: NodePort