apiVersion : v1
kind : Service
metadata:
  name: postgres-mlflow
  labels:
    env: prod
    owner: user
spec:
  selector:
    app : postgres-mlflow  # Selecting PODS
  ports:
    - name      : postgres-mlflow
      protocol  : TCP
      targetPort: 5432  # Port on POD
      port      : 5432